name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  

      - name: Install dependencies
        run: |
          ./gradlew build  # O el comando específico para tu proyecto

      - name: Build APK
        run: |
          ./gradlew assembleDebug  # O el comando específico para tu proyecto

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-apk
          path: app/build/outputs/apk/debug/app-debug.apk  
