name: Build APK

on:
  push:
    branches:
      - master  # Cambia esto si tu rama principal es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'  # Usa 'gradle' en lugar de 'maven'

    - name: Build with Gradle
      run: ./gradlew build  # Asegúrate de que este comando sea correcto

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-apk
        path: app/build/outputs/apk/debug/app-debug.apk  # Cambia esta ruta según la ubicación de tu APK
